### ISSUE TITLE
Flickr ibb.co

### ISSUE THREAD

**Issue by eplayerclick** [if1y/M3U8-on-Image-Hosting#1]
hello can we use ibbco or hls .. .does script still work?>

**Comment by if1y** [comment]
Sorry, it only supports the two websites, as you can see through the files' name.
But you can try to adjust the code :)

**Comment by eplayerclick** [comment]
I will try tell you if i succed.

**Comment by eplayerclick** [comment]
Also can this work with a m3u8 i already have from nginx rtmp for example?

**Comment by if1y** [comment]
For the two given examples:
- `aliexpress.py` requires a `.m3u8` input with video split already.
- `juejin.py` requires a video file input. FFmpeg will split it for you first.

**Comment by eplayerclick** [comment]
Ok, i am very bad with python this is why i keep asking you.
![image](https://user-images.githubusercontent.com/90185126/132335915-8936b2ca-a3f5-44d3-83d7-2dc940cd2264.png)

**Comment by eplayerclick** [comment]
I am not from china btw, nor do i have a CH IP

**Comment by if1y** [comment]
The API might be expired after two years.

**Comment by eplayerclick** [comment]
Okay, do you think you can remake the code a little? Aliexpress  code is interesting because no need for ffmpeg but works with for example nginx rtmp output

**Comment by if1y** [comment]
Please make yourself.
This repo is example for technical research only, but not for pratical use.
Once the website provider adds a rule to verify, everything your did will be in ruin.
